apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cortxserver.service.headless.name }}
  namespace: {{ .Values.namespace }}
  labels:
    cortx.io/service-type: {{ .Values.cortxserver.serviceType }}
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    app: {{ .Values.cortxserver.name }}
    cortx.io/service-type:  {{ .Values.cortxserver.serviceType }}
---    
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Values.cortxserver.name }}
    cortx.io/service-type:  {{ .Values.cortxserver.serviceType }}
  name: {{ .Values.cortxserver.name }}
  namespace: {{ .Values.namespace }}
spec:
  podManagementPolicy: Parallel
  serviceName: {{ .Values.cortxserver.service.headless.name }}
  replicas: {{ .Values.cortxserver.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.cortxserver.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.cortxserver.name }}
        name: cortx-server
        cortx.io/service-type: cortx-server
        cortx.io/hax-enabled: "true"
        cortx.io/service-domain: {{ .Values.cortxserver.service.headless.name }}
    spec:
      subdomain: {{ .Values.cortxserver.service.headless.name }}
      setHostnameAsFQDN: true
      serviceAccountName: {{ .Values.cortxserver.serviceaccountname }}
      volumes:
        - name: {{ .Values.cortxserver.cfgmap.volmountname }}
          configMap:
            name: {{ .Values.cortxserver.cfgmap.name }}
        - name: {{ .Values.cortxserver.sslcfgmap.volmountname }}
          configMap:
            name: {{ .Values.cortxserver.sslcfgmap.name }}
        - name: machine-id
          emptyDir: {}
        - name: local-path-pv
          emptyDir: {}
          # TODO CORTX-28968 Evaluate as volumeClaimTemplate as well
          #persistentVolumeClaim:
          #  claimName: {{ .Values.cortxserver.localpathpvc.name }}
        - name: {{ .Values.cortxserver.secretname }}
          secret:
            secretName: {{ .Values.cortxserver.secretname }}
      initContainers:
      - name: cortx-setup
        image: {{ .Values.cortxserver.image }}
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
        args:
          {{- if eq .Values.cortxserver.image "ghcr.io/seagate/centos:7" }}
          - sleep $(shuf -i 5-10 -n 1)s
          {{- else }}
          - export MACHINE_ID=$(hostname --fqdn);
            echo "Storing MACHINE_ID of '${MACHINE_ID}' in '${MACHINE_ID_PATH}'.";
            echo "${MACHINE_ID}" > ${MACHINE_ID_PATH};
            /opt/seagate/cortx/provisioner/bin/cortx_deploy -n ${MACHINE_ID} -f /etc/cortx/solution -c yaml:///etc/cortx/cluster.conf;
            sleep 180s;
          {{- end }}
        volumeMounts:
          - name: {{ .Values.cortxserver.cfgmap.volmountname }}
            mountPath: {{ .Values.cortxserver.cfgmap.mountpath }}
          - name: {{ .Values.cortxserver.sslcfgmap.volmountname }}
            mountPath: {{ .Values.cortxserver.sslcfgmap.mountpath }}
          - name: machine-id
            mountPath: {{ .Values.cortxserver.machineid.mountpath }}
          - name: local-path-pv
            mountPath: {{ .Values.cortxserver.localpathpvc.mountpath }}
          - name: {{ .Values.cortxserver.secretname }}
            mountPath: /etc/cortx/solution/secret
            readOnly: true
        env:
          - name: MACHINE_ID_PATH
            value: "{{ .Values.cortxserver.machineid.mountpath }}/id"
        ports:
        - containerPort: 5050
      containers:
        - name: cortx-rgw
          image: {{ .Values.cortxserver.image }}
          imagePullPolicy: IfNotPresent
          {{- if eq .Values.cortxserver.image  "ghcr.io/seagate/centos:7" }}
          command: ["/bin/sleep", "3650d"]
          {{- else }}
          command:
            - /bin/sh
          args:
            - -c
            - /opt/seagate/cortx/rgw/bin/rgw_setup start -c yaml:///etc/cortx/cluster.conf;
          {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxserver.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxserver.cfgmap.mountpath }}
            - name: {{ .Values.cortxserver.sslcfgmap.volmountname }}
              mountPath: {{ .Values.cortxserver.sslcfgmap.mountpath }}
            - name: machine-id
              mountPath: {{ .Values.cortxserver.machineid.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxserver.localpathpvc.mountpath }}
          ports:
          - name: rgw-http
            containerPort: 22751
            protocol: TCP
          - name: rgw-https
            containerPort: 23001
            protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
        - name: cortx-hax
          image: {{ .Values.cortxserver.image }}
          imagePullPolicy: IfNotPresent
          {{- if eq .Values.cortxserver.image  "ghcr.io/seagate/centos:7" }}
          command: ["/bin/sleep", "3650d"]
          {{- else }}
          command:
            - /bin/sh
          args:
            - -c
            - /opt/seagate/cortx/hare/bin/hare_setup start --config yaml:///etc/cortx/cluster.conf;
          {{- end }}
          volumeMounts:
            - name: {{ .Values.cortxserver.cfgmap.volmountname }}
              mountPath: {{ .Values.cortxserver.cfgmap.mountpath }}
            - name: {{ .Values.cortxserver.sslcfgmap.volmountname }}
              mountPath: {{ .Values.cortxserver.sslcfgmap.mountpath }}
            - name: machine-id
              mountPath: {{ .Values.cortxserver.machineid.mountpath }}
            - name: local-path-pv
              mountPath: {{ .Values.cortxserver.localpathpvc.mountpath }}
          ports:
          - name: hax
            containerPort: {{ .Values.cortxserver.hax.port | int }}
            protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
